Module6 task3
htmlacademy-react/437501-what-to-watch-7 pull request #11
Opened 2021-07-27 18:07 UTC by Borabola

2021-07-27 19:19 UTC, DmitryMarkov requested changes
Не могу запустить докально так как есть ошибки сборки, надо исправить:

![image](https://user-images.githubusercontent.com/9193608/127214808-0f97e2b9-a170-4847-bd4f-8c5606d80818.png)

2021-07-27 19:19 UTC, DmitryMarkov commented on project/src/components/pages/add-review/add-review.jsx
> +  isCurrentLoaded: state.isCurrentLoaded,
Так более понятно

```suggestion
  isCurrentFilmLoaded: state.isCurrentLoaded,
```

2021-07-27 19:19 UTC, DmitryMarkov commented on project/src/components/pages/film/film.jsx
> +    const resetFilmState = () => {
Я не думаю, что это нужно, можешь объяснить зачем?

2021-07-27 19:19 UTC, DmitryMarkov commented on project/src/components/pages/film/film.jsx
> +          {showenfilmsQnt < similarFilms.length && <BtnShowMore onBtnClick={showMoreFilmsHandler}/>}
название переменной showenfilmsQnt не соответствует критерию

2021-07-27 19:19 UTC, DmitryMarkov commented on project/src/components/pages/film/film.jsx
> +  }),
это уже встречается не первый раз, надо вынести в переменную

2021-07-27 19:19 UTC, DmitryMarkov commented on project/src/components/pages/film/film.jsx
> +            <Tabs currentFilm={currentFilm}  />
комменты лучше грузить сразу в этом компоненте и передавать

2021-07-27 19:19 UTC, DmitryMarkov commented on project/src/components/tabs/tabs.jsx
> +//import {reviewListProp} from '../../components/tabs/review.prop';
комменты кода запрещены

2021-07-27 19:19 UTC, DmitryMarkov commented on project/src/store/api-actions.js
> +    .then(({data}) => dispatch(ActionCreator.loadCurrentComments(data.map((item) => adaptComment(item)))))
не вижу смысла адаптировать комменты, можно использовать структуру которая приходит с сервера

2021-07-27 19:19 UTC, DmitryMarkov commented on project/src/store/api-actions.js
> +    .catch(() => dispatch(ActionCreator.redirectToRoute(AppRoute.PAGE_NOT_FOUND)))
это можно сделать через middleware, потому что редиректы также понадобятся с несуществующего плеера, add_review - везде где есть id

2021-07-28 17:05 UTC, Borabola commented on project/src/components/pages/add-review/add-review.jsx
> +    const resetFilmState = () => {
Чтобы обнулить данные о текущем фильме в сторе. Или если загрузка не произошла то будет экран загрузки. Значи этот блок убираю

2021-07-28 17:53 UTC, Borabola commented on project/src/components/pages/film/film.jsx
> +            <Tabs currentFilm={currentFilm}  />
Почему, ведь вкладку с комментариями могут вообще не открыть?

2021-07-29 17:48 UTC, DmitryMarkov requested changes
Если переключиться на вкладку Reviews и обновить страницу, то возникает ошибка

![image](https://user-images.githubusercontent.com/9193608/127540322-6840f361-a279-4819-bf7b-a67873cbbf42.png)

Если на странице http://localhost:3000/mylist обновить страницу пару раз подряд, то выкидывает на /login, хотя я залогинен.

Это ошибки то возникают, то нет

2021-07-29 17:48 UTC, DmitryMarkov commented on project/src/components/pages/add-review/add-review.jsx
> +//import {ActionCreator} from '../../../store/action';
комменты кода

2021-07-29 17:48 UTC, DmitryMarkov commented on project/src/components/pages/film/film.jsx
> +  const [showenFilmsQnt, setShowenFilmsQnt] = useState(FilmsQnt.SIMILAR);
Qnt - сокращение, они запрещены критерием. Можно использовать слово Count

2021-07-29 17:48 UTC, DmitryMarkov commented on project/src/components/review-form/review-form.jsx
> +        isFormValide: validateForm(),
Где-то здесь есть ошибка, так как я набираю больше 40 символов коммента, потом ставлю оценку, но ошибка все еще есть и кнопка Post заблокирована. Чтобы разблокировать, надо переключиться на текст снова, изменить его и тогда разблокируется. Так не должно быть

![image](https://user-images.githubusercontent.com/9193608/127539813-29f55269-aeac-427f-9d7f-2f803749e9ff.png)

2021-07-31 10:47 UTC, DmitryMarkov approved these changes
Задание выполнено

2021-07-31 10:47 UTC, DmitryMarkov commented on project/src/components/tabs/details.jsx
> +          <span className="film-card__details-value">{Array.isArray(currentFilm.starring) ? currentFilm.starring.map((item) => <span key={item}>{item}<br/></span>) : ''}
Более короткий способ записи такой:

```suggestion
          <span className="film-card__details-value">{Array.isArray(currentFilm.starring) && currentFilm.starring.map((item) => <span key={item}>{item}<br/></span>)}
```

2021-07-31 10:47 UTC, DmitryMarkov commented on project/src/services/api.js
> +/**axios.post(url, data)
комменты

2021-07-31 10:47 UTC, DmitryMarkov commented on project/src/services/api.js
> +    if (response !== undefined && response.status === HttpCode.UNAUTHORIZED) {
Тоже есть более короткий способ, но не знаю, поддерживается ли он линтером Академии

```suggestion
    if (response?.status === HttpCode.UNAUTHORIZED) {
```

2021-07-31 10:47 UTC, merged