Module3 task1
htmlacademy-react/437501-what-to-watch-7 pull request #5
Opened 2021-06-20 14:59 UTC by Borabola

2021-06-22 20:50 UTC, DmitryMarkov requested changes
Задание выполнено не до конца

2021-06-22 20:50 UTC, DmitryMarkov commented on project/src/components/app/app.jsx
> +          <AddReview filmList={filmList} />
Зачем передавать сюда список фильмов?

2021-06-22 20:50 UTC, DmitryMarkov commented on project/src/components/app/app.jsx
> +          <Player filmVideo={filmList[0].filmVideo} filmPoster={filmList[0].filmPoster} />
Сюда данные тоже должны передаваться из других компонентов а не роутера

2021-06-22 20:50 UTC, DmitryMarkov commented on project/src/components/app/app.jsx
> +          <ReviewFormPage filmVideo={filmList[0].filmVideo} filmPoster={filmList[0].filmPoster} />
И сюда

2021-06-22 20:50 UTC, DmitryMarkov commented on project/src/components/film-card/film-card.jsx
> +function FilmCard({filmTitle, imgName, filmVideo, filmPoster}) {
лучше передавать объект фильма целиком

2021-06-22 20:50 UTC, DmitryMarkov commented on project/src/components/film-card/film-card.jsx
> +        <Link to={AppRoute.FILM} className="small-film-card__link">{filmTitle}</Link>
в ссылке надо указывать id фильма

2021-06-22 20:50 UTC, DmitryMarkov commented on project/src/components/film-list/film-list.jsx
> +  const [activeFilm, setActiveFilm] = useState({id: null});
Не реализована смена id при наведении курсора на карточку

2021-06-22 20:50 UTC, DmitryMarkov commented on project/src/components/film-card/film-card.jsx
> +function FilmCard({filmTitle, imgName, filmVideo, filmPoster}) {
Нет обработчика наведения на карточку

2021-06-22 20:50 UTC, DmitryMarkov commented on project/src/components/film-list/film-list.prop.js
> +  PropTypes.shape({
Я бы оставил только сам shape здесь, а в компонентах использовал бы от контекста либо массив либо отдельно

2021-06-22 20:50 UTC, DmitryMarkov commented on project/src/components/page-footer/page-footer.jsx
> +        <Link to={AppRoute.MAIN} className="logo__link logo__link--light">
Нет такого маршрута

2021-06-22 20:50 UTC, DmitryMarkov commented on project/src/components/pages/add-review/add-review.jsx
> +                <Link to="/add-review" className="btn film-card__button">Add review</Link>
надо использовать маршруты из перечисления `AppRoute`, а здесь вообще ссылка на саму себя получается

2021-06-22 20:50 UTC, DmitryMarkov commented on project/src/components/pages/add-review/add-review.jsx
> +function AddReview({filmList}) {
Не реализовано:

> Реализуйте сохранение введённых в форму данных в state компонента.

2021-06-22 20:50 UTC, DmitryMarkov commented on project/src/components/pages/film/film.jsx
> +            <Logo />
В этом компоненте надо показывать данные фильма, по которому случился переход с карточки

2021-06-22 20:50 UTC, DmitryMarkov commented on project/src/components/pages/sing-in/sing-in.jsx
>  function SingIn() {
Компонент должен быть переименован (sign-in)

2021-06-22 20:50 UTC, DmitryMarkov commented on project/src/components/review-form-page/review-form-page.jsx
> +function ReviewFormPage() {
Этот компонент должен использоваться в `AddReview`

2021-06-22 20:50 UTC, DmitryMarkov commented on project/src/components/review-form/review-form.jsx
> +    setRating(value);
не работает. при выборе рейтинга значение в стейте не меняется

2021-06-22 20:50 UTC, DmitryMarkov commented on project/src/components/review-form-page/review-form-page.jsx
> +            <a href="main.html" className="logo__link">
Ссылка не работает

2021-06-22 20:50 UTC, DmitryMarkov commented on project/src/const.js
> +  REVIEW_FORM_PAGE: '/add-review',
это должен быть путь ADD_REVIEW

2021-06-22 20:50 UTC, DmitryMarkov commented on project/src/mocks/films.js
> +const filmList = [
Нет моков на reviews

2021-06-24 05:37 UTC, Borabola commented on project/src/components/app/app.jsx
> +          <AddReview filmList={filmList} />
На странице http://localhost:9999/films/:id/review  в нижней части выводится список фтльмов

2021-06-24 07:15 UTC, Borabola commented on project/src/components/review-form/review-form.jsx
> +    setRating(value);
поправила

2021-06-24 07:16 UTC, Borabola commented on project/src/components/review-form-page/review-form-page.jsx
> +            <a href="main.html" className="logo__link">
поправила

2021-06-28 12:27 UTC, DmitryMarkov reviewed
Всё ещё много замечаний, но основные пункты ТЗ выполнены. Продолжаем работу, исправляя замечания по ходу (в следующем PR)

2021-06-28 12:27 UTC, DmitryMarkov commented on project/src/components/pages/add-review/add-review.jsx
> +  const filmId = useParams();
название неверное, это не filmId, а весь объект параметров. Надо либо переименовать либо сделать деструктуризацию

2021-06-28 12:27 UTC, DmitryMarkov commented on project/src/components/pages/add-review/add-review.jsx
> +                <a href={url} className="breadcrumbs__link">Add review</a>
Здесь ссылки не должно быть (сама на себя получается, а сейчас вообще на главную)

2021-06-28 12:27 UTC, DmitryMarkov commented on project/src/components/pages/add-review/add-review.jsx
> +                <Link to={`/films/${filmId.id}/`}  className="breadcrumbs__link">{currentFilm.name}</Link>
слэш лишний, в роутах его нет

```suggestion
                <Link to={`/films/${filmId.id}`}  className="breadcrumbs__link">{currentFilm.name}</Link>
```

2021-06-28 12:27 UTC, DmitryMarkov commented on project/src/components/pages/add-review/add-review.jsx
> +                <img src="img/avatar.jpg" alt="User avatar" width="63" height="63" />
с аватара везде ссылка должна быть на `MyList`, вообще хидеры и футеры лучше вынести в отдельные компоненты, сейчас идет копирование кода во всех страницах

2021-06-28 12:27 UTC, DmitryMarkov commented on project/src/components/pages/film/film.jsx
>                  <p>Gustave prides himself on providing first-className service to the hotel’s guests, including satisfying the sexual needs of the many elderly women who stay there. When one of Gusta
Почему часть описания осталась в шаблоне? :)

2021-06-28 12:27 UTC, DmitryMarkov commented on project/src/components/pages/film/film.jsx
>                    <span className="film-rating__level">Very good</span>
Оценка должна рассчитываться из рейтинга

2021-06-28 12:27 UTC, DmitryMarkov commented on project/src/components/pages/film/film.jsx
>                <div className="film-card__buttons">
ссылка на Плеер должна быть

2021-06-28 12:27 UTC, DmitryMarkov commented on project/src/components/pages/film/film.jsx
> +                <p className="film-card__starring"><strong>Starring: {currentFilm.starring.map((item) => `${item}, `)}and other</strong></p>
одна запятая в конце лишняя, подумай как можно убрать

2021-06-28 12:27 UTC, DmitryMarkov commented on project/src/components/pages/film/film.jsx
> +          <FilmList films={films} />
при нажатии на ссылки фильмов там не происходит переход, попробуй найти причину и исправить (подсказка: используй хуки)

2021-06-28 12:27 UTC, DmitryMarkov commented on project/src/components/review-block/review-block.jsx
> +          <time className="review__date" dateTime="2016-12-24">{reviewDate}</time>
аттрибут dateTime должен высчитываться

2021-06-28 12:27 UTC, DmitryMarkov commented on project/src/components/review-form/review-form.jsx
> +          <input className="rating__input" id="star-1" type="radio" name="rating" defaultValue="1" onChange= {onRatingChange} />
Это можно (и нужно) делать в цикле. принцип DRY

2021-06-28 12:27 UTC, merged

2021-07-01 14:01 UTC, Borabola commented on project/src/components/pages/film/film.jsx
> +          <FilmList films={films} />
Со страниц типа этой ../films/5 есть переход по клику на другой фильм. В другом месте нет перехода?